---
title: "tidy data"
author: "Kaila Boyer"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(readxl)
```

```{r}
pulse_df <- read_sas("public_pulse_data.sas7bdat") %>% janitor::clean_names()
```

## Pivot longer
```{r}
pulse_tidy <- 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    values_to = "bdi", 
    names_prefix = "bdi_score") %>% 
  mutate( 
    visit = replace(visit, visit == "bl", "00m"), 
    visit = factor(visit))
```
Don't use gather(), always use pivot_longer()


## Pivot wider
making up a results data table

```{r}
analysis_df <- 
  tibble(
    group = c("treatment", "treatment", "control", "control"), 
    time = c("a", "b", "a", "b"), 
    group_mean = c(4, 8, 3, 6)
  )

analysis_df %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "group_mean"
  ) %>% 
  knitr::kable()
```
Don't use spread(), always use pivot_wider()

## bind_rows 
import the LotR movie data 

```{r}
fellowship_df <- 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_rings")

two_towers_df <- 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_df <- 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")

lotr_df <- 
  bind_rows(fellowship_df, two_towers_df, return_df) %>% 
  janitor::clean_names() %>% 
  pivot_longer( 
    female:male, 
    names_to = "sex", 
    values_to = "words") %>% 
  relocate(movie)
```

## joins
Look at FAS data. Imports and cleans the litters and pups dataframes. 

```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day_of_tx"), 3) %>% 
  relocate(litter_number) %>% 
  mutate(dose = str_to_lower(dose))

pups_df <- 
  read_csv("data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))
```

Joining the datasets 

```{r}
fas_df <- 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  relocate(litter_number, dose, day_of_tx)
```



